from dataclasses import dataclass

@dataclass
class Artifact:
    """
    An individual item generated by a class within the Jenerator ecosystem.

    Attributes:
        data (any): E.g., PIL image from imagejenerator, string/dict from textjenerator, etc.
        item_extras (dict): any additional metadata related to this artifact (e.g., seed, token count
        if this is not derivable outside the generator itself, etc.)
    """
    data: Any 
    item_extras: dict = field(default_factory=dict)

