from abc import ABC, abstractmethod
from typing import List, Dict, Any, Tuple

from basejenerator.generator_output import GeneratorOutput
from basejenerator.artifact import Artifact

class BaseGenerator(ABC):
    """
    Base class with common attributes and methods GenAI models locally.
    """

    def __init__(self, config: Dict[str, Any]):
        """
        Initializes the generator with a config dict.

        Args:
            config (dict): Configuration dictionary.
        """
        self.config = config
        self.model = None
        

    @abstractmethod
    def load(self):
        """
        Abstract method to load the model into memory, and run any other initialisation
        steps needed.
        
        Subclasses must implement this to load the specific model and assign 
        it to `self.model`.
        """
        pass


    @abstractmethod
    def prepare(self):
        """
        Reset lifecycle without tearing down the model - e.g., reset torch generators,
        clear cache, etc.
        """
        pass


    def generate(self) -> GeneratorOutput:
        """
        The public API that runs inference.

        Returns:
            GeneratorOutput        
        """
        artifacts, global_extras = self.generate_impl()

        return GeneratorOutput(
            batch=artifacts,
            extras=global_extras
        )


    @abstractmethod
    def generate_impl(self) -> Tuple[List[Artifact], Dict[str, Any]]:
        """
        Abstract method containing the core generation logic.

        Subclasses must implement this to run the inference and return artifacts and params.

        Returns:
            artifacts (List[Artifact]): A list of Artifact objects containing the artifacts generated by the model
            global_extras (Dict): Dictionary of any generation (i.e., not artifact specific) metadata
        """
        pass
    

    def _quick_wrap(self, raw_data: list) -> List[Artifact]:
        """
        Helper for subclasses to wrap artifacts into the Artfact class.
        """
        return [Artifact(data=item, item_extras={}) for item in raw_data]


    @abstractmethod
    def teardown(self):
        """
        Purge the model from memory, empty cache, run garbage collector, etc. 
        Clears the slate to avoid bleed between inference runs.
        """
        pass

