from dataclasses import dataclass, field
from abc import ABC, abstractmethod
import uuid

class BaseArtifact(ABC):
    """
    An individual item generated by a class within the Jenerator ecosystem.

    Attributes:
        data (any): E.g., PIL image from imagejenerator, string/dict from textjenerator, etc.
        item_extras (dict): any additional metadata related to this artifact (e.g., seed, token count
        if this is not derivable outside the generator itself, etc.)
    """

    def __init__(self, data):
        self.artifact_id: str = uuid.uuid4().hex[:8]
        self.root_artifact_id: str = ""
        self.parent_artifact_id: str = ""
        self.data: Any 
        self.item_extras: dict = field(default_factory=dict)
        self.extension: str
        self.generation_time: float = 0.0
        self.case_id: str = ""

    @abstractmethod
    def save(self, path):
        """
        Subclasses must implement and define how artifacts are saved.
        """
        pass

