from dataclasses import dataclass

class BaseArtifact:
    """
    An individual item generated by a class within the Jenerator ecosystem.

    Attributes:
        data (any): E.g., PIL image from imagejenerator, string/dict from textjenerator, etc.
        item_extras (dict): any additional metadata related to this artifact (e.g., seed, token count
        if this is not derivable outside the generator itself, etc.)
    """

    def __init__(self, data):
        self.data: Any 
        self.item_extras: dict = field(default_factory=dict)


    @abstractmethod
    def save(self, path):
        """
        Subclasses must implement and define how artifacts are saved.
        """
        pass

