# from PIL import Image
from basejenerator.artifacts.base_artifact import BaseArtifact

class PILArtifact(BaseArtifact):
    """
    Holds a PIL image generated by a class within the Jenerator ecosystem, and a
    method that can be used to save it.

    Attributes:
        data (any): PIL image.
        item_extras (dict): any additional metadata related to this artifact (e.g., seed, token count etc., if these are not derivable outside the generator itself, etc.)
    """

    def __init__(self, data, item_extras):
        super().__init__(data)
        self.data = data 
        self.item_extras = item_extras
        self.extension = ".png"

    def save(self, path):
        """
        Subclasses must implement and define how artifacts are saved.
        """
        self.data.save(path + ".jpg")
