# from PIL import Image
from basejenerator.artifacts.base_artifact import BaseArtifact

class TextArtifact(BaseArtifact):
    """
    Holds a text response generated by a class within the Jenerator ecosystem, and a
    method that can be used to save it.

    Attributes:
        data (str): text response from the generator.
        item_extras (dict): any additional metadata related to this artifact (e.g., token count, where not derivable outside the generator itself)
    """

    def __init__(self, data, item_extras):
        super().__init__(data)
        self.data = data 
        self.item_extras = item_extras
        self.extension = ".txt"


    def save(self, path):
        """
        Subclasses must implement and define how artifacts are saved.
        """
        with open(path, "w") as file:
            file.write(self.data)
